AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  BasicLambdaFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.7
      Timeout: 15
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref BasicApi
            Path: /
            Method: GET
      InlineCode: |
        import time
        def handler(event, context):
          time.sleep(15)
          return { 'body': 'Hello SAM!', 'statusCode': 200 }
  BasicApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "Basic API"
        paths:
          "/":
            get:
              responses:
                "200":
                  description: "200 response"
                  content: 
                    text/plain:
                      schema:
                        type: "string"
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws
                passthroughBehavior: "when_no_match"
                requestParameters:
                  "integration.request.header.X-Amz-Invocation-Type": "'Event'"
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BasicLambdaFn.Arn}/invocations"